ENV/Prestamos/Scripts/prestamos_faisl/polls/urls.py
from django.conf.urls import url
from . import views
#namespace: /polls/
app_name = 'polls'
urlpatterns = [
	url(r'^$', views.index, name='home_polls'),
	url(r'^centros', views.listar_centros, name='centros'),
	url(r'^insertar_centro', views.insertar_centro, name='insertar_centro'),
	url(r'^eliminar_centro', views.eliminar_centro, name='eliminar_centro'),
	url(r'^profesores', views.listar_profesores, name='profesores'),
	url(r'^insertar_profesor', views.insertar_profesor, name='insertar_profesor'),
	url(r'^eliminar_profesor', views.eliminar_profesor, name='eliminar_profesor'),
	url(r'^materiales', views.listar_materiales, name='materiales'),
	url(r'^insertar_material', views.insertar_material, name='insertar_material'),
	url(r'^eliminar_material', views.eliminar_material, name='eliminar_material'),
	url(r'^prestamos', views.listar_prestamos, name='prestamos'),
	url(r'^insertar_prestamo', views.insertar_prestamo, name='insertar_prestamo'),
	url(r'^eliminar_prestamo', views.eliminar_prestamo, name='eliminar_prestamo'),



]

ENV/Prestamos/Scripts/prestamos_faisl/prestamos_faisl/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^$', views.index_1, name='home_principal'),
]

ENV/Prestamos/Scripts/prestamos_faisl/polls/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Colegios(models.Model):
    id_colegio = models.AutoField(db_column='ID_colegio', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=100)  # Field name made lowercase.
    ciudad = models.CharField(db_column='Ciudad', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'colegios'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Materiales(models.Model):
    id_material = models.AutoField(db_column='ID_MATERIAL', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='NOMBRE', max_length=100)  # Field name made lowercase.
    numero_identificador = models.IntegerField(db_column='NUMERO_IDENTIFICADOR', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'materiales'


class Prestamo(models.Model):
    id_prestamos = models.AutoField(db_column='ID_PRESTAMOS', primary_key=True)  # Field name made lowercase.
    id_profesor = models.ForeignKey('Profesores', models.DO_NOTHING, db_column='ID_PROFESOR')  # Field name made lowercase.
    id_material = models.ForeignKey(Materiales, models.DO_NOTHING, db_column='ID_MATERIAL')  # Field name made lowercase.
    fecha_inicio = models.CharField(db_column='FECHA_INICIO', max_length=15)  # Field name made lowercase.
    fecha_fin = models.CharField(db_column='FECHA_FIN', max_length=15, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'prestamo'


class Profesores(models.Model):
    id_profesor = models.AutoField(db_column='ID_PROFESOR', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='NOMBRE', max_length=100)  # Field name made lowercase.
    apellido_1 = models.CharField(db_column='APELLIDO_1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    apellido_2 = models.CharField(db_column='APELLIDO_2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    telefono = models.IntegerField(db_column='TELEFONO', blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profesores'


class ProfesoresColegios(models.Model):
    identificacion_profesor = models.ForeignKey(Profesores, models.DO_NOTHING, db_column='Identificacion_profesor')  # Field name made lowercase.
    identificacion_colegio = models.ForeignKey(Colegios, models.DO_NOTHING, db_column='Identificacion_colegio')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profesores_colegios'
        unique_together = (('identificacion_profesor', 'identificacion_colegio'),)

ENV/Prestamos/Scripts/prestamos_faisl/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Colegios, Profesores, Prestamo, Materiales

# Create your views here.
# def index(request):
#	     latest_question_list = Colegios.objects.order_by('-id_colegio')[:200]
#	    template = loader.get_template('polls/index.html')
#	    context = {'latest_question_list' : latest_question_list}
#	    return HttpResponse(template.render(context, request))

###########################################################################
#Si se accede sin poner /polls/ se redirige.
def index_1(request):
	return HttpResponseRedirect('/polls/')

def index(request):
	return render(request, 'polls/index.html')
###########################################################################

def listar_centros(request):
	try:
		lista_colegios = Colegios.objects.all()
	except Colegios.DoesNotExist:
		#raise Http404 ("Error al listar colegios.")
		return render(request, 'polls/http4.html')
	context = {'lista_colegios' : lista_colegios}
	return render(request, 'polls/centros.html', context)

def insertar_centro(request):
	try:
		new_college = Colegios.objects.create(nombre = request.POST['nombre_colegio'], ciudad = request.POST['ciudad'])
	except:
		#raise Http404("Error al insertar centro.")
		return render(request, 'polls/http404.html')
	new_college.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def eliminar_centro(request):
	try:
		college = Colegios.objects.filter(nombre = request.POST['nombre_colegio']).delete()
	except:
		#raise Http404 ("Error al eliminar centro.")
		return render(request, 'polls/http404.html')
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

###########################################################################
def listar_profesores(request):
	try:
		lista_profesores = Profesores.objects.all()
	except:
		raise Http404("Error al listar los profesores.")
		return render(request, 'polls/http404.html')
	context = {'lista_profesores' : lista_profesores}
	return render(request, 'polls/profesores.html', context)

def insertar_profesor(request):
	try:
		new_profesor = Profesores.objects.create(nombre = request.POST['nombre_profesor'], apellido_1 = request.POST['apellido_1'], apellido_2 = request.POST['apellido_2'], telefono = request.POST['telefono'], email = request.POST['email'])
	except:
		raise Http404("Error al insertar profesor.")
		return render(request, 'polls/http404.html')
	new_profesor.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def eliminar_profesor(request):
	try:
		profesor = Profesores.objects.filter(nombre = request.POST['nombre_profesor'], apellido_1 = request.POST['apellido_1'], apellido_2 = request.POST['apellido_2']).delete()
	except:
		raise Http404("Error al eliminar profesor.")
		return render(request, 'polls/http404.html')
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

###########################################################################

def listar_materiales(request):
	try:
		lista_materiales = Materiales.objects.all()
	except:
		#raise Http404("Error al listar los materiales. ")
		return render(request, 'polls/http404.html')
	context={'lista_materiales': lista_materiales}
	return render(request, 'polls/materiales.html', context)

def insertar_material(request):
	try:
		new_material = Materiales.objects.create(nombre = request.POST['nombre'], numero_identificador= request.POST['numero_identificador'])
	except:
		#raise Http404("Error al insertar material.")
		return render(request, 'polls/http404.html')
	new_material.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def eliminar_material(request):
	try:
		material = Materiales.objects.filter(nombre = request.POST['nombre'], numero_identificador= request.POST['numero_identificador']).delete()
	except:
		#raise Http404("Error al eliminar material.")
		return render(request, 'polls/http404.html')
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

###########################################################################

def listar_prestamos(request):
	try:
		prestamos_list = Prestamo.objects.all()
		profesores_list = Profesores.objects.all()
		materiales_list = Materiales.objects.all();
	except Colegios.DoesNotExist:
		raise Http404("Error al listar prestamos.")
		return render(request, 'polls/http4.html')
	context = {'prestamos_list' : prestamos_list,'profesores_list' : profesores_list, 'materiales_list' : materiales_list,}
	return render(request, 'polls/prestamos.html', context)

def insertar_prestamo(request):
	try:
		profesor = Profesores.objects.get(nombre = request.POST.get("nombre"), apellido_1 = request.POST.get("apellido_1"))
		material = Materiales.objects.get(nombre = request.POST.get("Material"), numero_identificador = request.POST.get("identificador"))
		prestamos = Prestamo(id_profesor = profesor, id_material = material, fecha_inicio = request.POST.get("fecha"), fecha_fin = request.POST.get("fecha_fin"))
	except:
		raise Http404("Error al insertar prestamo.")
		return render(request, 'polls/http404.html')
	prestamos = Prestamo(id_profesor = profesor, id_material = material, fecha_inicio = request.POST.get("fecha"))
	prestamos.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def eliminar_prestamo(request):
	try:
		profesor = Profesores.objects.get(nombre = request.POST.get("nombre"), apellido_1 = request.POST.get("apellido_1"))
		material = Materiales.objects.get(nombre = request.POST.get("Material"), numero_identificador = request.POST.get("identificador"))
		prestamos = Prestamo.objects.get(id_profesor = profesor, id_material = material)
	except:
		raise Http404("Error al eliminar prestamo.")
		return render(request, 'polls/http404.html')
	prestamos.delete()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/centros.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Centros</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<table class="box">
		<form action="{% url 'polls:insertar_centro'%}" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Insertar Centro</h3></td></tr>
		<tr><td><label>Nombre Colegio</label></td>
		<td><input type="textbox" name="nombre_colegio"/></td></tr><br>
		<tr><td><label>Ciudad</label></td>
		<td><input type="textbox" name="ciudad"/></td></tr><br>
		<tr><td><input type="submit" name="insert" value="Insertar"></td></tr>
		</form>
		<form action="{% url 'polls:eliminar_centro'%}" method="POST">	
		{% csrf_token %}
		<tr><td><label>Eliminar Centro</label></td></tr>
		<tr><td><label>Nombre</label></td>	
		<td><input type="textbox" name="nombre_colegio"/></td></tr>
		<tr><td><input type="submit" name="delete" value="Eliminar"></td></td></tr>
		</form>
	</table>
	{% if lista_colegios %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th>
	 	<th><td><h3>CIUDAD</h3></td></th</tr>
	    {% for question in lista_colegios %}
	       <tr>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.ciudad }}</label></td></th>
	       </tr>
	    {% endfor %}
	</table>
	{% else %}
	<p>No hay centros para mostrar.</p>
	{% endif %}
</body>
</html>

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/http404.html
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="result_style.css">
		<meta charset="utf-8">
	</head>
	<body>
		<header><a href="/">Home</a></header>
		<h1>Http Error: 404</h1>
		<img src="https://c1.staticflickr.com/3/2692/4323598471_89e24792cc_b.jpg">
	</body>
</html>

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<meta charset="utf-8">
	<title>Home</title>
</head>
<body>
	<h1>HOME</h1>
	<ul>
		<li><a href="centros">Colegios</a></li>
	</ul>
	<ul>
		<li><a href="profesores">Profesores</a></li>
	</ul>
	<ul>
		<li><a href="materiales">Materiales</a></li>
	</ul>
	<ul>
		<li><a href="prestamos">Prestamos</a></li>
	</ul>
	<?php phpinfo(); ?>
</body>
</html>

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/materiales.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Materiales</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<table class="box">
		<form action="{% url 'polls:insertar_material'%}" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Insertar Material</h3></td></tr>
		<tr><td><label>Nombre Material</label></td>
		<td><input type="textbox" name="nombre"/></td></tr><br>
		<tr><td><label>Numero Identificador</label></td>
		<td><input type="number" name="numero_identificador"/></td></tr><br>
		<tr><td><input type="submit" name="insert" value="Insertar"></td></tr>
		</form>
		<form action="{% url 'polls:eliminar_material'%}" method="POST">	
		{% csrf_token %}
		<tr><td><h3>Eliminar Material</h3></td></tr>
		<tr><td><label>Nombre</label></td>	
		<td><input type="textbox" name="nombre"/></td></tr>
		<tr><td><label>Numero Identificador</label></td>	
		<td><input type="number" name="numero_identificador"/></td></tr>
		<tr><td><input type="submit" name="delete" value="Eliminar"></td></td></tr>
		</form>
	</table>
	{% if lista_materiales %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th>
	 	<th><td><h3>NUMERO</h3></td></th</tr>
	    {% for question in lista_materiales %}
	       <tr>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.numero_identificador }}</label></td></th>
	       </tr>
	    {% endfor %}
	</table>
	{% else %}
	<p>No materials are available.</p>
	{% endif %}
</body>
</html>

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/prestamos.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Buscar Centro</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:5%;
			    top:10%;
			    bottom:0;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<h1>
		Insertar o eliminar Prestamo
	</h1>

	<table class="box">
		<form action="{% url 'polls:insertar_prestamo' %}" method="POST">
		{% csrf_token %}
			<tr><td><h3>Insertar Prestamo</h3></td>
			<tr><td><label>Nombre Profesor</label></td>
			<td><input type="textbox" name="nombre"/></td></tr>
			<tr><td><label>Apellido 1</label></td>
			<td><input type="textbox" name="apellido_1"/></td></tr>
			<tr><td><label>Nombre Material</label></td>
			<td><input type="textbox" name="Material"/></td></tr>
			<tr><td><label>Indentificador material</label></td>
			<td><input type="textbox" name="identificador"/></td></tr>
			<tr><td><label>Fecha inicio</label></td>
			<td><input type="textbox" name="fecha"/></td></tr>
			<tr><td><label>Fecha fin</label></td>
			<td><input type="textbox" name="fecha_fin"/></td></tr>
			<tr><td><input type="submit" name="insert"/></td></tr>
			</form>
		<form action="{% url 'polls:eliminar_prestamo' %}" method="POST">
		{% csrf_token %}
			<tr><td><h3>Eliminar Prestamo</h3></td>
			<tr><td><label>Nombre Profesor</label></td>
			<td><input type="textbox" name="nombre"/></td></tr>
			<tr><td><label>Apellido 1</label></td>
			<td><input type="textbox" name="apellido_1"/></td></tr>
			<tr><td><label>Nombre Material</label></td>
			<td><input type="textbox" name="Material"/></td></tr>
			<tr><td><label>Indentificador material</label></td>
			<td><input type="textbox" name="identificador"/></td></tr>
			<tr><td><input type="submit" name="delete"/></td></tr>
		</form>
	</table>
	<table>
		<tr>
			<th><td><h4>NOMBRE</h4></td></th>
			<th><td><h4>APELLIDO_1</h4></td></th>
			<th><td><h4>APELLIDO_2</h4></td></th>
			<th><td><h4>EMAIL</h4></td></th>
			<th><td><h4>TELEFONO</h4></td></th>
			<th><td><h4>MATERIAL</h4></td></th>
			<th><td><h4>ID</h4></td></th>
			<th><td><h4>FECHA INICIO</h4></td></th>
			<th><td><h4>FECHA FIN</h4></td></th>

		</tr>
		{% if prestamos_list %}
		    {% for prestamo in prestamos_list %}
		       	<tr><th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_profesor.nombre}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_1}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_2}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_profesor.email}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_profesor.telefono}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_material.nombre}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.id_material.numero_identificador}}</label></td></th>
				<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.fecha_inicio}}</label></td></th>
		       	<th><td><label href="/myapp/{{ prestamo.id }}/">{{ prestamo.fecha_fin}}</label></td></th></tr>

		    {% endfor %}
    	{% else %}
    		<h2>No hay Prestamos realizados.</h2>
    	{% endif %}
    </table>
</body>
</html>

ENV/Prestamos/Scripts/prestamos_faisl/polls/templates/polls/profesores.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Profesores</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Volver</a></header>
	<table class="box">
		<form action="{% url 'polls:insertar_profesor'%}" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Insertar Profesor</h3></td></tr>
		<tr><td><label>Nombre Profesor</label></td>
		<td><input type="textbox" name="nombre_profesor"/></td></tr><br>
		<tr><td><label>Primer Apellido</label></td>
		<td><input type="textbox" name="apellido_1"/></td></tr><br>
		<tr><td><label>Segundo Apellido</label></td>
		<td><input type="textbox" name="apellido_2"/></td></tr><br>
		<tr><td><label>Teléfono</label></td>
		<td><input type="textbox" name="telefono"/></td></tr><br>
		<tr><td><label>Email</label></td>
		<td><input type="textbox" name="email"/></td></tr><br>
		<tr><td><input type="submit" name="insert" value="Insertar"></td></tr>
		</form>
		<form action="{% url 'polls:eliminar_profesor'%}" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Eliminar Profesor</h3></td></tr>
		<tr><td><label>Nombre Profesor</label></td>	
		<td><input type="textbox" name="nombre_profesor"/></td></tr>
		<tr><td><label>Primer Apellido</label></td>
		<td><input type="textbox" name="apellido_1"/></td></tr><br>
		<tr><td><label>Segundo Apellido</label></td>
		<td><input type="textbox" name="apellido_2"/></td></tr><br>
		<tr><td><input type="submit" name="delete" value="Eliminar"></td></td></tr>
		</form>
	</table>
	{% if lista_profesores %}
		<table>
			<tr>
				<th><td><h3>NOMBRE</h3></td></th>
				<th><td><h3>APELLIDO 1</h3></td></th>
				<th><td><h3>APELLIDO 2</h3></td></th>
				<th><td><h3>EMAIL</h3></td></th>
				<th><td><h3>TELÉFONO</h3></td></th>
			</tr>
		    {% for profesor in lista_profesores %}
				<tr>
				<th><td><label href="/polls/{{ profesor.id }}/">{{ profesor.nombre }}</label></td></th>
				<th><td><label href="/polls/{{ profesor.id }}/">{{ profesor.apellido_1 }}</label></td></th>
				<th><td><label href="/polls/{{ profesor.id }}/">{{ profesor.apellido_2 }}</label></td></th>
				<th><td><label href="/polls/{{ profesor.id }}/">{{ profesor.email }}</label></td></th>
				<th><td><label href="/polls/{{ profesor.id }}/">{{ profesor.telefono }}</label></td></th>
		       </tr>
		    {% endfor %}
	    </table>
	{% else %}
	    <p>No hay profesores.</p>
	{% endif %}
</body>
</html>