Prestamos/prestamos_faisl/polls/urls.py
from django.conf.urls import url
from . import views
#namespace: /polls/
app_name = 'polls'
urlpatterns = [
	url(r'^$', views.index, name='home'),
	url(r'^search', views.search, name='search'),
	url(r'^insertPrestamo', views.insertPrestamo, name='insertPrestamo'),
	url(r'^insert', views.insert, name='insert'),
	url(r'^delete', views.delete, name='delete'),
	url(r'^deleteMaterial', views.deleteMaterial, name="d_material"),
]

Prestamos/prestamos_faisl/prestamos_faisl/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^materials', views.listMaterials, name='mainMaterials'),
    url(r'^list_prestamos/', views.prestamos_list, name='list_pres'),
    url(r'^inserter/', views.insert_form, name='insert'),
    url(r'^inserterPrestamo/', views.insert_prestamo_form, name='inserterPrestamo'),
    url(r'^form/', views.formcolegios, name='formColegios'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='home'),
]

Prestamos/prestamos_faisl/polls/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Colegios(models.Model):
    id_colegio = models.AutoField(db_column='ID_colegio', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=100)  # Field name made lowercase.
    ciudad = models.CharField(db_column='Ciudad', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'colegios'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Materiales(models.Model):
    id_material = models.AutoField(db_column='ID_MATERIAL', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='NOMBRE', max_length=100)  # Field name made lowercase.
    numero_identificador = models.IntegerField(db_column='NUMERO_IDENTIFICADOR', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'materiales'


class Prestamo(models.Model):
    id_prestamos = models.AutoField(db_column='ID_PRESTAMOS', primary_key=True)  # Field name made lowercase.
    id_profesor = models.ForeignKey('Profesores', models.DO_NOTHING, db_column='ID_PROFESOR')  # Field name made lowercase.
    id_material = models.ForeignKey(Materiales, models.DO_NOTHING, db_column='ID_MATERIAL')  # Field name made lowercase.
    fecha_inicio = models.CharField(db_column='FECHA_INICIO', max_length=15)  # Field name made lowercase.
    fecha_fin = models.CharField(db_column='FECHA_FIN', max_length=15, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'prestamo'


class Profesores(models.Model):
    id_profesor = models.AutoField(db_column='ID_PROFESOR', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='NOMBRE', max_length=100)  # Field name made lowercase.
    apellido_1 = models.CharField(db_column='APELLIDO_1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    apellido_2 = models.CharField(db_column='APELLIDO_2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    telefono = models.IntegerField(db_column='TELEFONO', blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profesores'


class ProfesoresColegios(models.Model):
    identificacion_profesor = models.ForeignKey(Profesores, models.DO_NOTHING, db_column='Identificacion_profesor')  # Field name made lowercase.
    identificacion_colegio = models.ForeignKey(Colegios, models.DO_NOTHING, db_column='Identificacion_colegio')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'profesores_colegios'
        unique_together = (('identificacion_profesor', 'identificacion_colegio'),)

Prestamos/prestamos_faisl/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Colegios, Profesores, Prestamo, Materiales
import datetime
import time
import pdb

# Create your views here.
# def index(request):
#	     latest_question_list = Colegios.objects.order_by('-id_colegio')[:200]
#	    template = loader.get_template('polls/index.html')
#	    context = {'latest_question_list' : latest_question_list}
#	    return HttpResponse(template.render(context, request))
def index(request):	
	return render(request, 'polls/index.html')

def listado(request):
	try:
		colegios_list = Colegios.objects.all()
	except Colegios.DoesNotExist:
		raise Http404("Colegios Error.")
		return render(request, 'polls/http4.html')
	context = {'latest_question_list' : colegios_list,}
	return render(request, 'polls/listado.html', context)
def formcolegios(request):
	try:
		question = Profesores.objects.all()
	except:
		return render(request, 'polls/http404.html')
	context = {'result' : question}
	return render(request, 'polls/result.html', context)
def search(request):
	try:
		search_text = Colegios.objects.get(nombre= request.POST['nombre_colegio'])
	except:
		return render(request, 'polls/http404.html')
	context = {'result' : search_text}
	return render(request,'polls/result_search_colleges.html', context)

def insert_form(request):
	try:
		colegios_list = Colegios.objects.all()
	except Colegios.DoesNotExist:
		raise Http404("Colegios Error.")
		return render(request, 'polls/http4.html')
	context = {'latest_question_list' : colegios_list,}
	return render(request, 'polls/insert_form.html',context)
def insert(request):
	try:
		new_college = Colegios.objects.create(nombre = request.POST['nombre_colegio'], ciudad = request.POST['ciudad'])
	except:
		return render(request, 'polls/http404.html')
	new_college.save()
	return HttpResponseRedirect('/')
def delete(request):
	try:
		college = Colegios.objects.filter(nombre = request.POST['nombre_colegio'], ciudad = request.POST['ciudad']).delete()
	except:
		return render(request, 'polls/http404.html')
	return HttpResponseRedirect('/')
def prestamos_list(request):
	try:
		prestamos_list = Prestamo.objects.all()
		profesores_list = Profesores.objects.all()
		materiales_list = Materiales.objects.all();
	except Colegios.DoesNotExist:
		raise Http404("Colegios Error.")
		return render(request, 'polls/http4.html')
	context = {'prestamos_list' : prestamos_list,
	'profesores_list' : profesores_list, 'materiales_list' : materiales_list,}
	return render(request, 'polls/list_Prestamos.html', context)
def insert_prestamo_form(request):
	try:
		prestamos_list = Prestamo.objects.all()
		profesores_list = Profesores.objects.all()
		materiales_list = Materiales.objects.all();
	except Colegios.DoesNotExist:
		raise Http404("Colegios Error.")
		return render(request, 'polls/http4.html')
	context = {'prestamos_list' : prestamos_list,
	'profesores_list' : profesores_list, 'materiales_list' : materiales_list,}
	return render(request, 'polls/insert_prestamo_form.html', context)
def insertPrestamo(request):
	try:
		profesor = Profesores.objects.get(nombre = request.POST.get("nombre"), apellido_1 = request.POST.get("apellido_1"))
		material = Materiales.objects.get(nombre = request.POST.get("Material"), numero_identificador = request.POST.get("identificador"))
		if Prestamo.objects.filter(material.nombre, material.id_material).exists():
			return HttpResponse("Ya esiste el prestamo")
		else:
			prestamos = Prestamo(id_profesor = profesor, id_material = material, fecha_inicio = request.POST.get("fecha"), fecha_fin = request.POST.get("fecha_fin"))
	except:
		raise Http404("prestamos insert Error.")
	prestamos.save()
	return HttpResponseRedirect('/')

def listMaterials(request):
	try:
		materials_list = Materiales.objects.all()
	except:
		raise Http404("list material Error.")
	context = {'materialsList' : materials_list}
	return render(request, 'polls/mainMaterials.html', context)
def deleteMaterial(request):
	return HttpResponse("0k")

Prestamos/prestamos_faisl/polls/templates/polls/delete_form.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Borrar Centro</title>
	<meta charset="utf-8">
</head>
<body>
	<header><a href="/">Home</a></header>
	<h1>
		Borrar Centro
	</h1>
	<form action="{% url 'polls:delete'%}" method="POST">	
	{% csrf_token %}	
	<input type="textbox" name="nombre_colegio"/>
	<input type="submit" name="delete">
	</form>
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/delete_prestamo_form.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Buscar Centro</title>
	<meta charset="utf-8">
</head>
<body>
	<header><a href="/">Home</a></header>
	<h1>
		buscar Centro
	</h1>
	<form action="{% url 'polls:deleteLoam'%}" method="POST">	
	{% csrf_token %}
	<table>
		<tr><td><label>Nombre Profesor</label></td>
		<td><input type="textbox" name="nombre"/></td></tr><br>
		<tr><td><label>Apellido 1</label></td>
		<td><input type="textbox" name="apellido_1"/></td></tr><br>
		<tr><td><label>Nombre Material</label></td>
		<td><input type="textbox" name="Material"/></td></tr><br>
		<tr><td><label>Indentificador material</label></td>
		<td><input type="textbox" name="identificador"/></td></tr><br>
		<tr><td><input type="submit" name="delete"/></td></tr>
	</table>
	</fo

Prestamos/prestamos_faisl/polls/templates/polls/form.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Buscar Centro</title>
	<meta charset="utf-8">
</head>
<body>
	<header><a href="/">Home</a></header>
	<h1>
		buscar Centro
	</h1>
	<form action="{% url 'polls:search'%}" method="POST">	
	{% csrf_token %}	
	<input type="textbox" name="nombre_colegio"/>
	<input type="submit" name="search"/>
	</form>
	{% if latest_question_list %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th></tr>
	    {% for question in latest_question_list %}
	       <tr><th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th></tr>
	    {% endfor %}
	</table>
	{% else %}
	<p>No polls are available.</p>
	{% endif %}
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/http404.html
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<header><a href="/">Home</a></header>
		<h1>Http Error: 404</h1>
		<img src="https://c1.staticflickr.com/3/2692/4323598471_89e24792cc_b.jpg">
	</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>Home</title>
</head>
<body>
	<h1>HOME</h1>
	<ul>
		<!--li><a href="/polls">Listado Colegios</a></li-->
		<!--<li><a href="/searcher">Buscar Centro</a></li>-->
		<li><a href="/inserter">Home Colegios</a></li>
		<!--li><a href="/deleter">Borrar Centro</a></li-->
	</ul>
	<ul>
		<li><a href="/form">Home Profesores</a></li>
		<!--<li><a href="">Buscar Profesor</a></li>>
		<li><a href="">Insertar Profesor</a></li>
		<li><a href="">Borrar Profesor</a></li-->
	</ul>
	<ul>
		<li><a href="/materials">Home Materiales</a></li>
		<!--li><a href="">Buscar Material</a></li>
		<li><a href="">Insertar Material</a></li>
		<li><a href="">Borrar Material</a></li-->
	</ul>
	<ul>
		<!--<li><a href="/list_prestamos">Listado Prestamos</a></li>-->
		<!--li><a href="/searcher_prestamos">Buscar Prestamos</a></li-->
		<li><a href="/inserterPrestamo">Home Prestamos</a></li>
		<!--li><a href="/deleteLoam">Borrar Prestamos</a></li-->
	</ul>
	<?php phpinfo(); ?>
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/insert_form.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Insertar Centro</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<table class="box">
		<form action="{% url 'polls:insert'%}" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Insertar Centro</h3></td></tr>
		<tr><td><label>Nombre Colegio</label></td>
		<td><input type="textbox" name="nombre_colegio"/></td></tr><br>
		<tr><td><label>Ciudad</label></td>
		<td><input type="textbox" name="ciudad"/></td></tr><br>
		<tr><td><input type="submit" name="insert" value="Insertar"></td></tr>
		</form>
		<form action="{% url 'polls:delete'%}" method="POST">	
		{% csrf_token %}
		<tr><td><label>Eliminar Centro</label></td></tr>
		<tr><td><label>Nombre</label></td>	
		<td><input type="textbox" name="nombre_colegio"/></td></tr>
		<tr><td><label>Ciudad</label></td>	
		<td><input type="textbox" name="ciudad"/></td></tr>
		<tr><td><input type="submit" name="delete" value="Eliminar"></td></td></tr>
		</form>
	</table>
	{% if latest_question_list %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th>
	 	<th><td><h3>CIUDAD</h3></td></th</tr>
	    {% for question in latest_question_list %}
	       <tr>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.ciudad }}</label></td></th>
	       </tr>
	    {% endfor %}
	</table>
	{% else %}
	<p>No polls are available.</p>
	{% endif %}
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/insert_prestamo_form.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Buscar Centro</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)

			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<h1>
		Insertar Prestamo
	</h1>
	<form action="{% url 'polls:insertPrestamo'%}" method="POST">	
		{% csrf_token %}
		<table class="box">
			<tr><td><label>Nombre Profesor</label></td>
			<td><input type="textbox" name="nombre"/></td></tr><br>
			<tr><td><label>Apellido 1</label></td>
			<td><input type="textbox" name="apellido_1"/></td></tr><br>
			<tr><td><label>Nombre Material</label></td>
			<td><input type="textbox" name="Material"/></td></tr><br>
			<tr><td><label>Indentificador material</label></td>
			<td><input type="textbox" name="identificador"/></td></tr><br>
			<tr><td><label>Fecha inicio</label></td>
			<td><input type="textbox" name="fecha"/></td></tr><br>
			<tr><td><label>Fecha fin</label></td>
			<td><input type="textbox" name="fecha_fin"/></td></tr><br>
			<tr><td><input type="submit" name="insert"/></td></tr>
		</table>
	</form>
	<table>
		<tr>
			<th><td><h4>NOMBRE</h4></td></th>
			<th><td><h4>APELLIDO_1</h4></td></th>
			<th><td><h4>APELLIDO_2</h4></td></th>
			<th><td><h4>EMAIL</h4></td></th>
			<th><td><h4>TELEFONO</h4></td></th>
			<th><td><h4>MATERIAL</h4></td></th>
			<th><td><h4>ID</h4></td></th>
			<th><td><h4>FECHA INICIO</h4></td></th>
			<th><td><h4>FECHA FIN</h4></td></th>
		</tr>
		{% if prestamos_list %}
		    {% for prestamo in prestamos_list %}
		       	<tr>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.nombre}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_1}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_2}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.email}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.telefono}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_material.nombre}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_material.numero_identificador}}</label></td></th>
			       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.fecha_inicio}}</label></td></th>
			    	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.fecha_fin}}</label></td></th>
		    	</tr>
		    {% endfor %}
    	{% else %}
    		<h2>No hay Prestamos realizados.</h2>
    	{% endif %}
    </table>
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/list_Prestamos.html
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
</head>
<header><a href="/">Home</a></header>
	<table>
		<tr>
			<th><td><h4>NOMBRE</h4></td></th>
			<th><td><h4>APELLIDO_1</h4></td></th>
			<th><td><h4>APELLIDO_2</h4></td></th>
			<th><td><h4>EMAIL</h4></td></th>
			<th><td><h4>TELEFONO</h4></td></th>
			<th><td><h4>MATERIAL</h4></td></th>
			<th><td><h4>ID</h4></td></th>
		</tr>
		{% if prestamos_list %}
		    {% for prestamo in prestamos_list %}
		       	<tr><th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.nombre}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_1}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.apellido_2}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.email}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_profesor.telefono}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_material.nombre}}</label></td></th>
		       	<th><td><label href="/polls/{{ prestamo.id }}/">{{ prestamo.id_material.numero_identificador}}</label></td></th></tr>
		    {% endfor %}
    	{% else %}
    		<h2>No hay Prestamos realizados.</h2>
    	{% endif %}
    </table>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/listado.html
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<header><a href="/">Home</a></header>
{% if latest_question_list %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th></tr>
	    {% for question in latest_question_list %}
	       <tr><th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th></tr>
	    {% endfor %}
    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Prestamos/prestamos_faisl/polls/templates/polls/mainMaterials.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<title>Insertar Centro</title>
	<meta charset="utf-8">
	<style type="text/css">
		.box {
			    position:fixed;
			    right:10%;
			    top:10%;
			    bottom:auto;
			    background: rgba(76, 175, 80, 0.3)
			}
	</style>
</head>
<body>
	<header><a href="/">Home</a></header>
	<table class="box">
		<form action="" method="POST">	
		{% csrf_token %}	
		<tr><td><h3>Insertar Material</h3></td></tr>
		<tr><td><label>Nombre Material</label></td>
		<td><input type="textbox" name="nombreMaterial"/></td></tr><br>
		<tr><td><label>Numero Identificador</label></td>
		<td><input type="textbox" name="numero_identificador"/></td></tr><br>
		<tr><td><input type="submit" name="insert" value="Insertar"></td></tr>
		</form>
		<form action="{%url 'polls:d_material'%}" method="POST">
		{% csrf_token %}
		<tr><td><h3>Eliminar Material</h3></td></tr>
		<tr><td><label>Nombre</label></td>	
		<td><input type="textbox" name="nombreMaterial"/></td></tr>
		<tr><td><label>Numero Identificador</label></td>	
		<td><input type="textbox" name="numero_identificador"/></td></tr>
		<tr><td><input type="submit" name="delete" value="Eliminar"></td></td></tr>
		</form>
	</table>
	{% if materialsList %}
	<table>
	 	<tr><th><td><h3>NOMBRE</h3></td></th>
	 	<th><td><h3>NUMERO</h3></td></th</tr>
	    {% for question in materialsList %}
	       <tr>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th>
	       		<th><td><label href="/polls/{{ question.id }}/">{{ question.numero_identificador }}</label></td></th>
	       </tr>
	    {% endfor %}
	</table>
	{% else %}
	<p>No materials are available.</p>
	{% endif %}
</body>
</html>

Prestamos/prestamos_faisl/polls/templates/polls/result.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="result_style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>Result</title>
</head>
<body>
	<header><a href="/">Home</a></header>
	{% if result %}
		<table>
			<tr>
				<th><td><h3>NOMBRE</h3></td></th>
				<th><td><h3>APELLIDO 1</h3></td></th>
				<th><td><h3>APELLIDO 2</h3></td></th>
				<th><td><h3>EMAIL</h3></td></th>
				<th><td><h3>TELÉFONO</h3></td></th>
			</tr>
		    {% for question in result %}
				<tr>
				<th><td><label href="/polls/{{ question.id }}/">{{ question.nombre }}</label></td></th>
				<th><td><label href="/polls/{{ question.id }}/">{{ question.apellido_1 }}</label></td></th>
				<th><td><label href="/polls/{{ question.id }}/">{{ question.apellido_2 }}</label></td></th>
				<th><td><label href="/polls/{{ question.id }}/">{{ question.email }}</label></td></th>
				<th><td><label href="/polls/{{ question.id }}/">{{ question.telefono }}</label></td></th>
		       </tr>
		    {% endfor %}
	    </table>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
</body>
</html>